import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/about">
          <a>About Us</a>
        </Link>
        <Link href="/colors">
          <a>Colors</a>
        </Link>
      </main>
    </div>
  )
}

export default Home
